// run: npm run seed
// wipes the places collection and inserts 100 famous Indian destinations
// add more objects to this array and re-run to expand the home page grid

const mongoose = require("mongoose");
const dotenv = require("dotenv");
const Place = require("../models/Place");

dotenv.config();

const places = [
  // ─── JAMMU & KASHMIR / LADAKH ──────────────────────────────────────────────
  {
    name: "Gulmarg",
    location: "Jammu & Kashmir",
    description: "Snow-capped hill station famous for the world's highest gondola ride and some of Asia's best ski slopes.",
    image: "https://images.unsplash.com/photo-1605538883669-825200433431?w=800&q=80",
    category: "Mountains",
    rating: 4.8,
  },
  {
    name: "Srinagar",
    location: "Jammu & Kashmir",
    description: "Dal Lake houseboats, Mughal gardens and floating vegetable markets — the summer capital of J&K has a rhythm all its own.",
    image: "https://images.unsplash.com/photo-1545389336-cf090694435e?w=800&q=80",
    category: "Cultural",
    rating: 4.7,
  },
  {
    name: "Pahalgam",
    location: "Jammu & Kashmir",
    description: "A scenic valley on the banks of the Lidder River, gateway to the Amarnath pilgrimage and the lush Betaab Valley.",
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80",
    category: "Adventure",
    rating: 4.6,
  },
  {
    name: "Sonamarg",
    location: "Jammu & Kashmir",
    description: "The Meadow of Gold — a breathtaking valley at 2800m surrounded by glaciers, snow peaks and alpine flowers.",
    image: "https://images.unsplash.com/photo-1609766856946-b4dc04d2b8d6?w=800&q=80",
    category: "Mountains",
    rating: 4.7,
  },
  {
    name: "Leh",
    location: "Ladakh",
    description: "A high-altitude desert town with ancient monasteries, fluttering prayer flags and a raw landscape that stops you in your tracks.",
    image: "https://images.unsplash.com/photo-1544015759-62c2d6cc12c0?w=800&q=80",
    category: "Mountains",
    rating: 4.9,
  },
  {
    name: "Pangong Lake",
    location: "Ladakh",
    description: "A 134km-long saltwater lake at 4350m whose water shifts from turquoise to indigo to violet as clouds move across it.",
    image: "https://images.unsplash.com/photo-1527631746610-bca00a040d60?w=800&q=80",
    category: "Lakes",
    rating: 4.9,
  },
  {
    name: "Nubra Valley",
    location: "Ladakh",
    description: "A high-altitude cold desert with Bactrian camels, sand dunes and the Diskit Monastery perched above the valley floor.",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    category: "Desert",
    rating: 4.8,
  },
  {
    name: "Zanskar Valley",
    location: "Ladakh",
    description: "One of India's most remote valleys, famous for the Chadar frozen river trek and untouched Buddhist culture.",
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80",
    category: "Adventure",
    rating: 4.8,
  },

  // ─── HIMACHAL PRADESH ──────────────────────────────────────────────────────
  {
    name: "Manali",
    location: "Himachal Pradesh",
    description: "A popular hill station in the Beas River valley, perfect for adventure sports, Rohtang snow and cosy cafes in Old Manali.",
    image: "https://images.unsplash.com/photo-1626621341169-32fda9930fc7?w=800&q=80",
    category: "Mountains",
    rating: 4.7,
  },
  {
    name: "Shimla",
    location: "Himachal Pradesh",
    description: "The former summer capital of British India, with a charming mall road, colonial architecture and pine-covered hillsides.",
    image: "https://images.unsplash.com/photo-1609766941272-dab4e350e7cd?w=800&q=80",
    category: "Hill Station",
    rating: 4.5,
  },
  {
    name: "Spiti Valley",
    location: "Himachal Pradesh",
    description: "A cold desert mountain valley with ancient monasteries, stark lunar landscapes and star-filled skies at 4000m.",
    image: "https://images.unsplash.com/photo-1626621341169-32fda9930fc7?w=800&q=80",
    category: "Offbeat",
    rating: 4.9,
  },
  {
    name: "Dharamshala",
    location: "Himachal Pradesh",
    description: "Home of the Dalai Lama and the Tibetan government-in-exile, nestled below the Dhauladhar range with stunning mountain views.",
    image: "https://images.unsplash.com/photo-1544015759-62c2d6cc12c0?w=800&q=80",
    category: "Spiritual",
    rating: 4.7,
  },
  {
    name: "McLeod Ganj",
    location: "Himachal Pradesh",
    description: "Little Lhasa in India — a buzzing Tibetan town with monasteries, momos, meditation retreats and mountain treks.",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    category: "Cultural",
    rating: 4.7,
  },
  {
    name: "Dalhousie",
    location: "Himachal Pradesh",
    description: "A quiet colonial hill station spread over five hills with views of the Pir Panjal and Dhauladhar ranges.",
    image: "https://images.unsplash.com/photo-1609766856946-b4dc04d2b8d6?w=800&q=80",
    category: "Hill Station",
    rating: 4.4,
  },
  {
    name: "Kasauli",
    location: "Himachal Pradesh",
    description: "A sleepy British-era cantonment town with colonial bungalows, monkey point views and barely any tourist rush.",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    category: "Hill Station",
    rating: 4.3,
  },
  {
    name: "Parvati Valley",
    location: "Himachal Pradesh",
    description: "A lush green river valley with the hot springs of Manikaran, trek routes to Kheerganga and a laid-back traveller vibe.",
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80",
    category: "Offbeat",
    rating: 4.6,
  },

  // ─── UTTARAKHAND ───────────────────────────────────────────────────────────
  {
    name: "Rishikesh",
    location: "Uttarakhand",
    description: "The yoga capital of the world, sitting where the Ganga flows out of the Himalayas — perfect for rafting, yoga and evening aarti.",
    image: "https://images.unsplash.com/photo-1591017683521-a3c8da5c01b4?w=800&q=80",
    category: "Spiritual",
    rating: 4.7,
  },
  {
    name: "Haridwar",
    location: "Uttarakhand",
    description: "One of Hinduism's seven sacred cities, where the Ganga touches the plains and the Har Ki Pauri ghat blazes with evening lamps.",
    image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&q=80",
    category: "Spiritual",
    rating: 4.6,
  },
  {
    name: "Nainital",
    location: "Uttarakhand",
    description: "A charming lake town in the Kumaon Hills with boating, cable cars and forested walks above the emerald Naini Lake.",
    image: "https://images.unsplash.com/photo-1527631746610-bca00a040d60?w=800&q=80",
    category: "Hill Station",
    rating: 4.5,
  },
  {
    name: "Mussoorie",
    location: "Uttarakhand",
    description: "The Queen of Hills, with the famous Lal Tibba viewpoint, Kempty Falls and a breezy Mall Road above the Doon Valley.",
    image: "https://images.unsplash.com/photo-1609766941272-dab4e350e7cd?w=800&q=80",
    category: "Hill Station",
    rating: 4.5,
  },
  {
    name: "Auli",
    location: "Uttarakhand",
    description: "India's premier skiing destination in winter, and a meadow with sweeping Nanda Devi views in summer.",
    image: "https://images.unsplash.com/photo-1605538883669-825200433431?w=800&q=80",
    category: "Adventure",
    rating: 4.7,
  },
  {
    name: "Kedarnath",
    location: "Uttarakhand",
    description: "One of the Char Dham pilgrimage sites, a Shiva temple at 3583m surrounded by the snow-clad Garhwal Himalayas.",
    image: "https://images.unsplash.com/photo-1544015759-62c2d6cc12c0?w=800&q=80",
    category: "Spiritual",
    rating: 4.8,
  },
  {
    name: "Jim Corbett National Park",
    location: "Uttarakhand",
    description: "India's oldest national park and a haven for Bengal tigers, with jeep safaris through dense sal forests and grasslands.",
    image: "https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=800&q=80",
    category: "Wildlife",
    rating: 4.6,
  },
  {
    name: "Chopta",
    location: "Uttarakhand",
    description: "The mini Switzerland of Uttarakhand — a pristine meadow with a trek to the ancient Tungnath temple at 3680m.",
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80",
    category: "Offbeat",
    rating: 4.7,
  },

  // ─── RAJASTHAN ─────────────────────────────────────────────────────────────
  {
    name: "Jaipur",
    location: "Rajasthan",
    description: "The Pink City — Hawa Mahal, Amber Fort, bazaars bursting with gems and block-printed textiles and food that's all heat and ghee.",
    image: "https://images.unsplash.com/photo-1477587458883-47145ed6736d?w=800&q=80",
    category: "Heritage",
    rating: 4.7,
  },
  {
    name: "Udaipur",
    location: "Rajasthan",
    description: "The City of Lakes, where white palaces float on still water and every rooftop gives you a view that should be on a postcard.",
    image: "https://images.unsplash.com/photo-1579003815008-c53b1b1efb3d?w=800&q=80",
    category: "Heritage",
    rating: 4.8,
  },
  {
    name: "Jodhpur",
    location: "Rajasthan",
    description: "The Blue City, dominated by the massive Mehrangarh Fort rising above a maze of indigo-painted houses.",
    image: "https://images.unsplash.com/photo-1477587458883-47145ed6736d?w=800&q=80",
    category: "Heritage",
    rating: 4.7,
  },
  {
    name: "Jaisalmer",
    location: "Rajasthan",
    description: "A golden sandstone city rising from the Thar Desert, with a living fort, camel safaris and nights sleeping under the stars.",
    image: "https://images.unsplash.com/photo-1549820881-e0b1e6f42e54?w=800&q=80",
    category: "Desert",
    rating: 4.8,
  },
  {
    name: "Pushkar",
    location: "Rajasthan",
    description: "A sacred lake town with the only Brahma temple in India, a famous camel fair in November and sunsets from the ghats.",
    image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&q=80",
    category: "Spiritual",
    rating: 4.5,
  },
  {
    name: "Ranthambore",
    location: "Rajasthan",
    description: "One of India's best places to spot Bengal tigers in the wild, with jeep safaris through ancient ruins and dry deciduous forest.",
    image: "https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=800&q=80",
    category: "Wildlife",
    rating: 4.7,
  },
  {
    name: "Bikaner",
    location: "Rajasthan",
    description: "A fort city in the Thar with the magnificent Junagarh Fort, camel breeding farms and the famous Bikaneri bhujia.",
    image: "https://images.unsplash.com/photo-1549820881-e0b1e6f42e54?w=800&q=80",
    category: "Heritage",
    rating: 4.4,
  },
  {
    name: "Mount Abu",
    location: "Rajasthan",
    description: "Rajasthan's only hill station with the extraordinary Dilwara Jain temples carved entirely from white marble.",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    category: "Hill Station",
    rating: 4.4,
  },
  {
    name: "Bundi",
    location: "Rajasthan",
    description: "An underrated gem — a blue-painted old town, a palace famous for its murals and a fort that Kipling wrote about.",
    image: "https://images.unsplash.com/photo-1579003815008-c53b1b1efb3d?w=800&q=80",
    category: "Offbeat",
    rating: 4.5,
  },

  // ─── KERALA ────────────────────────────────────────────────────────────────
  {
    name: "Alleppey",
    location: "Kerala",
    description: "The Venice of the East — sleep on a houseboat, drift through palm-fringed canals and watch the sun set over the backwaters.",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80",
    category: "Backwaters",
    rating: 4.8,
  },
  {
    name: "Munnar",
    location: "Kerala",
    description: "Rolling tea plantations, misty mornings and waterfalls tucked between the Western Ghats at 1600m.",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    category: "Hill Station",
    rating: 4.7,
  },
  {
    name: "Varkala",
    location: "Kerala",
    description: "A cliffside beach town with a stretch of red laterite cliffs above the Arabian Sea, mineral springs and a beach for serious relaxing.",
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80",
    category: "Beach",
    rating: 4.5,
  },
  {
    name: "Thekkady",
    location: "Kerala",
    description: "The Periyar Wildlife Sanctuary with boat rides on a forest lake where elephants wade to the water's edge.",
    image: "https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=800&q=80",
    category: "Wildlife",
    rating: 4.6,
  },
  {
    name: "Wayanad",
    location: "Kerala",
    description: "A green district of mist-covered hills, tribal culture, ancient caves and some of the most scenic drives in South India.",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    category: "Nature",
    rating: 4.6,
  },
  {
    name: "Kovalam",
    location: "Kerala",
    description: "Three crescent-shaped beaches with a lighthouse, Ayurvedic resorts and the gentle rhythm of a South Indian coastal town.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    category: "Beach",
    rating: 4.4,
  },

  // ─── KARNATAKA ─────────────────────────────────────────────────────────────
  {
    name: "Coorg",
    location: "Karnataka",
    description: "The Scotland of India — coffee estates, cardamom forests, waterfall hikes and the warmly hospitable Kodava culture.",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    category: "Hill Station",
    rating: 4.7,
  },
  {
    name: "Hampi",
    location: "Karnataka",
    description: "A UNESCO World Heritage site — ancient Vijayanagara ruins scattered among giant boulders in a surreal, timeless landscape.",
    image: "https://images.unsplash.com/photo-1524399820186-0571c81abea5?w=800&q=80",
    category: "Heritage",
    rating: 4.8,
  },
  {
    name: "Mysore",
    location: "Karnataka",
    description: "The City of Palaces, famous for its illuminated Mysore Palace, silk sarees, aromatic sandalwood and the grand Dasara festival.",
    image: "https://images.unsplash.com/photo-1524399820186-0571c81abea5?w=800&q=80",
    category: "Heritage",
    rating: 4.6,
  },
  {
    name: "Gokarna",
    location: "Karnataka",
    description: "A small temple town on the coast with some of Karnataka's finest beaches — from Om Beach to the peaceful Half Moon Beach.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    category: "Beach",
    rating: 4.5,
  },
  {
    name: "Chikmagalur",
    location: "Karnataka",
    description: "The birthplace of Indian coffee — rolling estates, the Mullayanagiri peak and forest treks through the Western Ghats.",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    category: "Hill Station",
    rating: 4.5,
  },

  // ─── GOA ───────────────────────────────────────────────────────────────────
  {
    name: "North Goa",
    location: "Goa",
    description: "Baga, Calangute, Anjuna — buzzing beach shacks, flea markets, legendary nightlife and the laid-back trance-music vibe of Goa.",
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80",
    category: "Beach",
    rating: 4.6,
  },
  {
    name: "South Goa",
    location: "Goa",
    description: "Quieter, cleaner beaches like Palolem and Agonda with fewer crowds, hammocks between palms and dolphin spotting trips.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    category: "Beach",
    rating: 4.7,
  },
  {
    name: "Old Goa",
    location: "Goa",
    description: "A UNESCO site with 16th century Portuguese basilicas, including the Basilica of Bom Jesus holding St. Francis Xavier's remains.",
    image: "https://images.unsplash.com/photo-1524399820186-0571c81abea5?w=800&q=80",
    category: "Heritage",
    rating: 4.5,
  },

  // ─── TAMIL NADU ────────────────────────────────────────────────────────────
  {
    name: "Ooty",
    location: "Tamil Nadu",
    description: "Queen of the Nilgiris — a hill station with a toy train ride, botanical gardens, eucalyptus forests and home-made chocolate.",
    image: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80",
    category: "Hill Station",
    rating: 4.5,
  },
  {
    name: "Kodaikanal",
    location: "Tamil Nadu",
    description: "A misty hill town at 2100m with a star-shaped lake, pine forests, waterfalls and some of the freshest air in South India.",
    image: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80",
    category: "Hill Station",
    rating: 4.5,
  },
  {
    name: "Madurai",
    location: "Tamil Nadu",
    description: "One of India's oldest living cities, home to the awe-inspiring Meenakshi Amman Temple with its towering, sculpture-covered gopurams.",
    image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&q=80",
    category: "Spiritual",
    rating: 4.7,
  },
  {
    name: "Mahabalipuram",
    location: "Tamil Nadu",
    description: "A coastal UNESCO site with 7th century rock-cut temples, the Shore Temple and sculptures carved straight out of living rock.",
    image: "https://images.unsplash.com/photo-1524399820186-0571c81abea5?w=800&q=80",
    category: "Heritage",
    rating: 4.6,
  },
  {
    name: "Kanyakumari",
    location: "Tamil Nadu",
    description: "India's southernmost tip where the Bay of Bengal, Arabian Sea and Indian Ocean meet — sunrises and sunsets from the same spot.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    category: "Spiritual",
    rating: 4.6,
  },
  {
    name: "Rameswaram",
    location: "Tamil Nadu",
    description: "A sacred island temple town connected to Sri Lanka by the legendary Rama Setu, with the magnificent Ramanathaswamy Temple.",
    image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&q=80",
    category: "Spiritual",
    rating: 4.6,
  },

  // ─── MAHARASHTRA ───────────────────────────────────────────────────────────
  {
    name: "Lonavala",
    location: "Maharashtra",
    description: "A monsoon favourite two hours from Mumbai — waterfalls, tiger point viewpoints, Bhushi Dam overflow and the famous chikki candy.",
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80",
    category: "Hill Station",
    rating: 4.3,
  },
  {
    name: "Mahabaleshwar",
    location: "Maharashtra",
    description: "Maharashtra's highest hill station, known for strawberry farms, Arthur's Seat viewpoints and pine-fresh air above the Sahyadri range.",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    category: "Hill Station",
    rating: 4.4,
  },
  {
    name: "Aurangabad",
    location: "Maharashtra",
    description: "Gateway to the Ajanta and Ellora caves — two UNESCO sites with 2000-year-old Buddhist murals and rock-cut temples.",
    image: "https://images.unsplash.com/photo-1524399820186-0571c81abea5?w=800&q=80",
    category: "Heritage",
    rating: 4.7,
  },
  {
    name: "Matheran",
    location: "Maharashtra",
    description: "India's smallest hill station and the only one with zero vehicles allowed — a peaceful plateau reached by a tiny toy train.",
    image: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80",
    category: "Hill Station",
    rating: 4.3,
  },
  {
    name: "Tarkarli",
    location: "Maharashtra",
    description: "Maharashtra's best-kept coastal secret — crystal-clear water, scuba diving, Malvani seafood and a beach without the Goa prices.",
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80",
    category: "Beach",
    rating: 4.4,
  },
  {
    name: "Nashik",
    location: "Maharashtra",
    description: "The wine capital of India with over 50 vineyards, the Trimbakeshwar Jyotirlinga and the sacred Godavari ghats.",
    image: "https://images.unsplash.com/photo-1591017683521-a3c8da5c01b4?w=800&q=80",
    category: "Spiritual",
    rating: 4.3,
  },

  // ─── UTTAR PRADESH & MADHYA PRADESH ───────────────────────────────────────
  {
    name: "Taj Mahal, Agra",
    location: "Uttar Pradesh",
    description: "A white marble monument to eternal love, one of the Seven Wonders of the World — no photograph does it justice.",
    image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&q=80",
    category: "Heritage",
    rating: 4.9,
  },
  {
    name: "Varanasi",
    location: "Uttar Pradesh",
    description: "Perhaps the world's oldest living city — the Ganges ghats, the dawn boat rides, the evening aarti and the relentless energy of life and death.",
    image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&q=80",
    category: "Spiritual",
    rating: 4.8,
  },
  {
    name: "Khajuraho",
    location: "Madhya Pradesh",
    description: "A UNESCO World Heritage site of stunning 10th century temples covered in intricate sculptural art, far in the middle of MP.",
    image: "https://images.unsplash.com/photo-1524399820186-0571c81abea5?w=800&q=80",
    category: "Heritage",
    rating: 4.7,
  },
  {
    name: "Orchha",
    location: "Madhya Pradesh",
    description: "A forgotten Bundela kingdom on the Betwa River — cenotaphs, palaces and temples that tourists haven't quite discovered yet.",
    image: "https://images.unsplash.com/photo-1579003815008-c53b1b1efb3d?w=800&q=80",
    category: "Offbeat",
    rating: 4.6,
  },
  {
    name: "Pachmarhi",
    location: "Madhya Pradesh",
    description: "The queen of Satpura — the only hill station in MP with waterfalls, caves, ancient rock paintings and dense tiger country.",
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80",
    category: "Hill Station",
    rating: 4.5,
  },
  {
    name: "Kanha National Park",
    location: "Madhya Pradesh",
    description: "The real-life inspiration for The Jungle Book — vast meadows, dense sal forest and one of India's best chances of spotting a tiger.",
    image: "https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=800&q=80",
    category: "Wildlife",
    rating: 4.8,
  },
  {
    name: "Bandhavgarh",
    location: "Madhya Pradesh",
    description: "India's highest density of Bengal tigers, a hill fort with ancient caves and morning safaris that give you goosebumps.",
    image: "https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=800&q=80",
    category: "Wildlife",
    rating: 4.8,
  },

  // ─── PUNJAB & NORTH INDIA ──────────────────────────────────────────────────
  {
    name: "Amritsar",
    location: "Punjab",
    description: "Home of the Golden Temple, the beating heart of Sikhism — the langar that feeds 100,000 people a day, the Wagah Border ceremony.",
    image: "https://images.unsplash.com/photo-1591017683521-a3c8da5c01b4?w=800&q=80",
    category: "Spiritual",
    rating: 4.9,
  },
  {
    name: "Delhi",
    location: "Delhi",
    description: "The capital where Old and New exist side by side — Mughal monuments, street food bazaars, modern art galleries and the best metro in India.",
    image: "https://images.unsplash.com/photo-1570168007204-ec0c4f3b4b1f?w=800&q=80",
    category: "Cultural",
    rating: 4.5,
  },

  // ─── NORTHEAST INDIA ───────────────────────────────────────────────────────
  {
    name: "Gangtok",
    location: "Sikkim",
    description: "Sikkim's cheerful capital with Kanchenjunga views on clear mornings, monastery hopping and momos that are the best you'll ever eat.",
    image: "https://images.unsplash.com/photo-1544015759-62c2d6cc12c0?w=800&q=80",
    category: "Mountains",
    rating: 4.6,
  },
  {
    name: "Darjeeling",
    location: "West Bengal",
    description: "Tea estates, the Toy Train, Tiger Hill sunrise with Kanchenjunga glowing orange — Darjeeling is the hill station that earns its legend.",
    image: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80",
    category: "Hill Station",
    rating: 4.7,
  },
  {
    name: "Shillong",
    location: "Meghalaya",
    description: "The Scotland of the East with a thriving music scene, living root bridges nearby, Ward's Lake and the cleanest air in northeast India.",
    image: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80",
    category: "Hill Station",
    rating: 4.5,
  },
  {
    name: "Cherrapunji",
    location: "Meghalaya",
    description: "One of the wettest places on Earth, with the magical double-decker living root bridges and viewpoints over the Bangladesh plains.",
    image: "https://images.unsplash.com/photo-1432923369571-7e32e9ad2588?w=800&q=80",
    category: "Nature",
    rating: 4.7,
  },
  {
    name: "Tawang",
    location: "Arunachal Pradesh",
    description: "A remote valley at 3048m with Asia's largest Buddhist monastery, war memorials and landscapes that feel like Tibet.",
    image: "https://images.unsplash.com/photo-1544015759-62c2d6cc12c0?w=800&q=80",
    category: "Spiritual",
    rating: 4.8,
  },
  {
    name: "Kaziranga",
    location: "Assam",
    description: "A UNESCO site with two-thirds of the world's one-horned rhinoceroses, elephant safaris and spectacular Himalayan backdrops.",
    image: "https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=800&q=80",
    category: "Wildlife",
    rating: 4.8,
  },
  {
    name: "Ziro Valley",
    location: "Arunachal Pradesh",
    description: "A lush plateau of pine forests and rice paddies, home to the Apatani tribe and an annual music festival under the open sky.",
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80",
    category: "Offbeat",
    rating: 4.7,
  },
  {
    name: "Majuli Island",
    location: "Assam",
    description: "The world's largest river island in the Brahmaputra — mask-making satras, Vaishnavite monasteries and sunsets over the river.",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80",
    category: "Cultural",
    rating: 4.6,
  },

  // ─── WEST BENGAL / ODISHA ─────────────────────────────────────────────────
  {
    name: "Sundarbans",
    location: "West Bengal",
    description: "The world's largest mangrove delta, a UNESCO site, and home to the Royal Bengal Tiger that swims between islands.",
    image: "https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=800&q=80",
    category: "Wildlife",
    rating: 4.6,
  },
  {
    name: "Kolkata",
    location: "West Bengal",
    description: "The City of Joy — a collage of colonial architecture, intellectual cafes, Durga Puja pandals and the world's best street food after Mumbai.",
    image: "https://images.unsplash.com/photo-1570168007204-ec0c4f3b4b1f?w=800&q=80",
    category: "Cultural",
    rating: 4.5,
  },
  {
    name: "Puri",
    location: "Odisha",
    description: "Home of the Jagannath Temple and a long sandy beach — one of the four Hindu dhams and the site of the spectacular Rath Yatra.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    category: "Spiritual",
    rating: 4.5,
  },
  {
    name: "Konark",
    location: "Odisha",
    description: "The 13th century Sun Temple built in the shape of a massive stone chariot — a UNESCO site and one of India's greatest architectural wonders.",
    image: "https://images.unsplash.com/photo-1524399820186-0571c81abea5?w=800&q=80",
    category: "Heritage",
    rating: 4.7,
  },
  {
    name: "Chilika Lake",
    location: "Odisha",
    description: "Asia's largest brackish water lagoon with Irrawaddy dolphins, hundreds of migratory bird species and a floating island temple.",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80",
    category: "Nature",
    rating: 4.5,
  },

  // ─── GUJARAT ───────────────────────────────────────────────────────────────
  {
    name: "Rann of Kutch",
    location: "Gujarat",
    description: "The world's largest salt desert, transformed into a white lunar landscape in winter and the venue for the Rann Utsav festival.",
    image: "https://images.unsplash.com/photo-1549820881-e0b1e6f42e54?w=800&q=80",
    category: "Desert",
    rating: 4.7,
  },
  {
    name: "Somnath",
    location: "Gujarat",
    description: "The first of the twelve Jyotirlinga shrines of Shiva, a temple rebuilt multiple times over centuries, standing at the sea's edge.",
    image: "https://images.unsplash.com/photo-1591017683521-a3c8da5c01b4?w=800&q=80",
    category: "Spiritual",
    rating: 4.5,
  },
  {
    name: "Gir Forest",
    location: "Gujarat",
    description: "The only place on Earth where Asiatic Lions live in the wild — jeep safaris through dry teak forest with a lion sighting rate above 90%.",
    image: "https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=800&q=80",
    category: "Wildlife",
    rating: 4.7,
  },
  {
    name: "Ahmedabad",
    location: "Gujarat",
    description: "India's first UNESCO World Heritage City — centuries-old pols, the Sabarmati Ashram, Kankaria Lake and the best Gujarati thali in existence.",
    image: "https://images.unsplash.com/photo-1570168007204-ec0c4f3b4b1f?w=800&q=80",
    category: "Heritage",
    rating: 4.4,
  },

  // ─── ANDHRA & TELANGANA ────────────────────────────────────────────────────
  {
    name: "Tirupati",
    location: "Andhra Pradesh",
    description: "The richest and most visited temple in the world — millions come to have their heads shaved and receive blessings at the Venkateswara shrine.",
    image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&q=80",
    category: "Spiritual",
    rating: 4.7,
  },
  {
    name: "Hyderabad",
    location: "Telangana",
    description: "The City of Nizams — Charminar, Golconda Fort, the best biryani in India and a tech-city energy that coexists with ancient Deccani culture.",
    image: "https://images.unsplash.com/photo-1570168007204-ec0c4f3b4b1f?w=800&q=80",
    category: "Cultural",
    rating: 4.5,
  },

  // ─── PONDICHERRY ───────────────────────────────────────────────────────────
  {
    name: "Pondicherry",
    location: "Tamil Nadu",
    description: "A French quarter with mustard-yellow colonial buildings, sea-facing promenades, Sri Aurobindo Ashram and a coffee culture unlike anywhere else.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    category: "Cultural",
    rating: 4.6,
  },

  // ─── ISLANDS ───────────────────────────────────────────────────────────────
  {
    name: "Andaman Islands",
    location: "Andaman & Nicobar",
    description: "Pristine white sand beaches, electric blue water, world-class scuba diving and the sobering Cellular Jail at Port Blair.",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80",
    category: "Island",
    rating: 4.9,
  },
  {
    name: "Lakshadweep",
    location: "Lakshadweep",
    description: "India's smallest union territory — a coral archipelago with lagoons so turquoise they look fake and snorkelling straight off the beach.",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80",
    category: "Island",
    rating: 4.8,
  },

  // ─── MORE OFFBEAT ─────────────────────────────────────────────────────────
  {
    name: "Lansdowne",
    location: "Uttarakhand",
    description: "A tiny Garhwal cantonment town with oak and rhododendron forests, practically zero tourist chaos and views all the way to the Himalayas.",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    category: "Offbeat",
    rating: 4.4,
  },
  {
    name: "Dhanaulti",
    location: "Uttarakhand",
    description: "A quiet village above Mussoorie with dense deodar forests, snow in winter and views of the Garhwal peaks — far fewer crowds than its famous neighbour.",
    image: "https://images.unsplash.com/photo-1609766856946-b4dc04d2b8d6?w=800&q=80",
    category: "Offbeat",
    rating: 4.5,
  },
  {
    name: "Mukteshwar",
    location: "Uttarakhand",
    description: "A ridge-top village with a Shiva temple, cliffside rock-climbing, apple orchards and clean cold air far from the typical hill station crowd.",
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80",
    category: "Offbeat",
    rating: 4.5,
  },
  {
    name: "Alibaug",
    location: "Maharashtra",
    description: "Mumbai's beach escape — a ferry ride across the bay, the Kulaba Fort on a rocky island, fresh kolambi (prawns) and a proper slow weekend.",
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80",
    category: "Beach",
    rating: 4.2,
  },
  {
    name: "Hampta Pass",
    location: "Himachal Pradesh",
    description: "A dramatic 4270m trek connecting the green Kullu Valley to the arid Lahaul desert — one of the most scenic crossings in the Indian Himalayas.",
    image: "https://images.unsplash.com/photo-1544015759-62c2d6cc12c0?w=800&q=80",
    category: "Adventure",
    rating: 4.8,
  },
  {
    name: "Pondicherry Auroville",
    location: "Tamil Nadu",
    description: "An experimental township of 3000 residents from 60 nations, built around the Matrimandir golden sphere and the idea of human unity.",
    image: "https://images.unsplash.com/photo-1591017683521-a3c8da5c01b4?w=800&q=80",
    category: "Spiritual",
    rating: 4.5,
  },
  {
    name: "Rohtang Pass",
    location: "Himachal Pradesh",
    description: "A 3978m mountain pass on the Manali highway, giving even first-time visitors a proper Himalayan snow experience.",
    image: "https://images.unsplash.com/photo-1605538883669-825200433431?w=800&q=80",
    category: "Adventure",
    rating: 4.5,
  },
  {
    name: "Bhedaghat",
    location: "Madhya Pradesh",
    description: "A gorge of 100-foot marble rocks along the Narmada river — a boat ride through white and rose-tinted cliffs at sunrise is unforgettable.",
    image: "https://images.unsplash.com/photo-1432923369571-7e32e9ad2588?w=800&q=80",
    category: "Nature",
    rating: 4.5,
  },
  {
    name: "Coimbatore",
    location: "Tamil Nadu",
    description: "The gateway to the Nilgiris and home of Isha Yoga Centre — a vibrant industrial city with the best filter coffee and idli in South India.",
    image: "https://images.unsplash.com/photo-1570168007204-ec0c4f3b4b1f?w=800&q=80",
    category: "Cultural",
    rating: 4.2,
  },
];

const seedPlaces = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("Connected to MongoDB");

    await Place.deleteMany();
    await Place.insertMany(places);

    console.log(`${places.length} places added successfully`);
    process.exit();
  } catch (error) {
    console.error("Seeding failed:", error.message);
    process.exit(1);
  }
};

seedPlaces();
